---
- name: Playbook
  hosts: ansible-node
  remote_user: vagrant

  tasks:
    - name: Variable check
      debug:
        msg: "env: {{ env }}"

    - name: Default list in vagrant directory
      shell: |
        ls -al /vagrant
      register: list
  
    - name: Print result
      debug:
        msg: "{{ list.stdout }}"